### ISSUE TITLE
No video thubmnail for iOS safari

### ISSUE THREAD

**Issue by grigory-bogush** [banthagroup/fslightbox-react#130]
It seems safari doesn't allow for video thumbnails in this case from what I have read.
The only way to display it seems to be the `poster` attribute, where a thumbnail image could be loaded.
In my opinion the ability to add this attribute to a `video` tag should be added, or a better still a custom video attribute should be allowed.

**Comment by grigory-bogush** [comment]
Oh, sorry, the functionality is there, I just didn't notice it. It's the `videosPosters` attribute.
And I don't think anything can be done about mobile safari not being up to speed.
I think the issue can be closed.
Only maybe a note about this browser quirk could be added to the documentation.

**Comment by banthagroup** [comment]
Clossing issue :)
