### ISSUE TITLE
Prevent load google fonts (@import url(https://fonts.googleapis.com/css?family=Roboto))

### ISSUE THREAD

**Issue by martinsura** [banthagroup/fslightbox-react#133]
Hello,

First - nice library. I have one question. Its possible to override default styles and prevent load google fonts from external site? (maybe style.js in src folder?) In my use-case i serve google fonts(roboto) locally from folder.

Thanks!

**Comment by piotrzdziarski** [comment]
Just released new version without Roboto font - replaced it with available in CSS Helvetica.

**Comment by martinsura** [comment]
Thanks!

**Comment by Tarpsvo** [comment]
Thanks! I've been wanting to request this for a while now, but never got around to it. Definitely nice to have one less font to load.
