### ISSUE TITLE
Remounting with lightbox open crashes (null is not an object (evaluating 'e.current.classList'))

### ISSUE THREAD

**Issue by Tarpsvo** [banthagroup/fslightbox-react#134]
Hi!

Thanks for this amazing lightbox.

I'm using Sentry for error logging in the live environment and am receiving an alarming number of crashes due to FSLightbox.

My FSLightbox implementation uses strictly images (image URLs).

```
const carouselImages = images.map(img => img.url);

...

<FsLightbox
  toggler={lightboxOpen}
  type="image"
  sources={carouselImages}
  slide={selectedImageIndex}
  disableLocalStorage
/>
```

The crash is reported as follows:

```
TypeError
null is not an object (evaluating 'e.current.classList')

[1]
{snip} h(k.a.createRef());return t}function F(e,t){var n=e.current.classList;n.contains(t)&&n.remove(t)}var B=250;function U(e){var t=this,n=e.comp {snip}

[2]
{snip} ==innerHeight&&o.set(!1);for(var e=0;e<i.sourcesCount;e++)F(l[e],u),e!==d.current&&n[e].negative(),r[e]&&c[e].current&&r[e].styleSize()}}(e) {snip}
```

Additional data about event:
```
[
  {
    currentTarget: [object Window],
    isTrusted: [Circular ~],
    target: [object Window],
    type: resize
  }
]
```

It has been reported a total of 219 times with the following browser stats:

% |   | Last Seen
-- | -- | --
39.73% | Chrome Mobile 78.0.3904 | 3 days ago
30.14% | Chrome 78.0.3904 | a day ago
11.42% | Mobile Safari 13.0.1 | 21 hours ago
9.13% | Mobile Safari 10.0 | 4 days ago
5.48% | Samsung Internet 10.2 | 3 days ago
4.11% | Samsung Internet 10.1 | 7 days ago

#### Update about reproducablity:

I found a way to reproduce it, so it might be an issue with the way I implement FsLightbox. I use it in a single-page app e-commerce project and FsLightbox is used to display product images.

It basically happens when the user navigates back using browser's back functionality when the FsLightbox is open. As it's a single page app and react router intercepts the back press, it just causes a re-render, but it does not completely re-render the FsLightbox - instead, it just changes the `sources` prop. This causes the scroll to still be blocked and throws the described error(s) when the window is resized. The scroll can be fixed by re-opening and closing the lightbox, but the `classList` errors persist.

See video: https://d.pr/v/mIw57V

I think I can fix it by forcing the lightbox to close on route change. Is it something you will consider handling as well? I believe the only way to detect this on the FsLightbox side is when the `sources` changes completely.

#### Updates about fixing:

Also tried setting the `key` prop, but it did not solve the described issue. It didn't seem to re-mount the FsLightbox component.

Even tried forcing a re-render using state:

```
const [fsLightboxRender, setFsLightboxRender] = useState(false);

useEffect(() => {
    setFsLightboxRender(false);
    setTimeout(() => setFsLightboxRender(true), 0);
  }, [product.id]);

...

{fsLightboxRender && (
  <FsLightbox
    toggler={lightboxOpen}
    type="image"
    sources={carouselImages}
    slide={selectedImageIndex}
    disableLocalStorage
    key={product.id}
  />
)}
```

It didn't work. :(

I think it boils down to remounting the component while the lightbox is open not working as intended?

**Comment by Tarpsvo** [comment]
Updated issue w/ steps to reproduce.

**Comment by piotrzdziarski** [comment]
I think I know what's the case - lightbox is not running close actions after unmount, so things like  events listeners persist. There is gonna be fix soon!

**Comment by piotrzdziarski** [comment]
Just released new version with fix for this issue.

**Comment by Tarpsvo** [comment]
Nice, just tested it and works perfectly. A huge thanks!
