### ISSUE TITLE
Slide number container too small to fit large numbers

### ISSUE THREAD

**Issue by TECHMAUS** [banthagroup/fslightbox-react#135]
### Summary
The slide-number-container width is too small to fit large numbers.

### Expected Behavior
When displaying a large number of images, the counter should remain in its top left position, expending its width to the right. 

### Actual Behavior

A max width of 55px is currently set on the container. Resulting in this behavior, where the number '354' is cut off at the left side:
<img width="1192" alt="Schermafbeelding 2019-12-26 om 15 29 50" src="https://user-images.githubusercontent.com/9018689/71479431-add2d380-27f4-11ea-940c-3f1a8d3ed9b8.png">

### Possible fixes

Position the slide-number-container with an absolute position, just like the toolbar.

**Comment by piotrzdziarski** [comment]
Issue was fixed in new version.
