### ISSUE TITLE
Pinch to zoom causes issues on mobile

### ISSUE THREAD

**Issue by websocket98765** [banthagroup/fslightbox-react#137]
### Expected behavior

On mobile, I expected to be able to pinch an image to zoom in, pan around, and pinch to zoom back out to default size.

### Actual behavior

- Pinching to zoom doesn't zoom.
- It can cause unexpected behavior like swiping images or more than one image being displayed. 

### A good example of pinch to zoom functionality

https://photoswipe.com/#&gid=1&pid=1

### How to reproduce

I tried this on mobile using both fslightbox and fslightbox pro by visiting fslightbox.com on a mobile phone.

**Comment by caseykey** [comment]
This is one of the tradeoffs for this module. It has awesome swipe support and supports custom sources like videos, but no zoom. If you are looking for zoom, checkout react-image-lightbox.

**Comment by websocket98765** [comment]
Thanks for the suggestion. I may have to do that because zoom on mobile is a necessity to meet user expectations IMO. Hopefully fslightbox also adds it sometime because there is a lot to like about fslightbox otherwise!

**Comment by crabzo** [comment]
+1

**Comment by onadeem1** [comment]
yes this would be excellent, its been tough to find a lightbox type app for react, I think this one is the closest with a few additions such as zoom and swipe to close

**Comment by binomialstew** [comment]
This should fix this issue:
https://github.com/banthagroup/fslightbox-react/pull/146

**Comment by binomialstew** [comment]
Fixed by:
https://github.com/banthagroup/fslightbox-react/pull/147
