### ISSUE TITLE
TypeError cannot read property 'length' of undefined [pro version]

### ISSUE THREAD

**Issue by driglou** [banthagroup/fslightbox-react#138]
After following the guide in README file and importing pro version of fslightbox-react to my modules, this is the error I am getting when I am adding FsLightbox element.

I am using gatsby fslightbox-react in gatsby

**Comment by piotrzdziarski** [comment]
Now lightbox uses **sources** prop instead of **urls**. I forget to update that in README. Just rename this prop and everything should works.

**Comment by driglou** [comment]
Yes that was the cause. It's working great now.

I know it's different questions, but if you would give a minute to clarify it would be great:
1. How do you pass text with the source? I know I could use a custom source where I wrap text and image elements in div, but is there a simplier solution to pass a label to source?
2. In provided demo you can either see labels or thumbnails, can you make to see them all?


Thank you.

**Comment by driglou** [comment]
Yes, changing **urls** to **sources** solved it. Thanks
