### ISSUE TITLE
Ability to set scale for image zoom

### ISSUE THREAD

**Issue by justin-snap** [banthagroup/fslightbox-react#141]
Currently the library zooms in with 0.25 scale increments. 

When a user needs to look at minute details in the images this takes quite a few clicks to make the image large enough or even bring it to its full size.

Setting image zoom increments in props would be a simple change.

This is a really USEFUL library especially for quick content-review use, but adding more customization via props would be AMAZING. Keep up the good work.

**Comment by piotrzdziarski** [comment]
Adden in pro version 1.4.0. Prop: **zoomIncrement**
