### ISSUE TITLE
height of 0px set on Custom Source

### ISSUE THREAD

**Issue by fantapop** [banthagroup/fslightbox-react#143]
I'm trying to https://www.npmjs.com/package/react-instagram-embed as a custom source.  For some reason by the time the instagram post loads, fslightbox has determined that the height is 0px and it sets this style on the component. I can manually delete this style after the post loads but every time I resize the page, its reset to 0px.

**Comment by piotrzdziarski** [comment]
Hi, try setting size of custom source manually e.g.

```
<FsLightbox
   customSources={[
      <div style={{ width: '1366px', height: '768px', background: 'yellow' }} />
   ]}
/>
```
Set dimensions are treated as maximal dimensions of custom source.
