### ISSUE TITLE
disableLocalStorage should disable all localStorage operations

### ISSUE THREAD

**Issue by Hypnosphi** [banthagroup/fslightbox-react#145]
Here are the ones currently not disabled:
https://github.com/banthagroup/fslightbox-react/blob/master/src/core/scrollbar/getScrollbarWidth.js#L6
https://github.com/banthagroup/fslightbox-react/blob/master/src/core/scrollbar/getScrollbarWidth.js#L23
https://github.com/banthagroup/fslightbox-react/blob/master/src/core/sources/creating/CreatingSourcesLocalStorageManager.js#L33

**Comment by piotrzdziarski** [comment]
FIxed in 1.6.1
