### ISSUE TITLE
Stop Videos on slide change

### ISSUE THREAD

**Issue by luchoster** [banthagroup/fslightbox-react#153]
This is an amazing lightbox, so thank you for that!

Is there a way to stop the videos from playing when I change the slide? If I start playing one video and then go to the next one, and play it, I can hear both videos playing. I added the `loadOnlyCurrentSource` and for some reason it worked last night, but I guess it was only a fluke, because today it has the default behavior, and I can see the same thing happening in the pro demo version.

Thanks!

**Comment by piotrzdziarski** [comment]
`loadOnlyCurrentSource` has nothing in common with videos.
In basic version it's not possible to pause videos on slide change, but it's possible in the pro version thanks to **onSlideChange** event. It takes as param FsLightbox instance. Unfortunately there is no previous slide number passed so you need to iterate through all sources:
```js
onSlideChange(fsLightbox) {
    const sources = fsLightbox.elements.sources;

    for (let i = 0; i < sources.length; i++) {
        const source = sources[i];
        if (source && source.tagName === 'VIDEO' && !source.paused) {
            source.pause();
        }
    }
}
```

**Comment by piotrzdziarski** [comment]
`loadOnlyCurrentSource` has nothing in common with videos.
In basic version it's not possible to pause videos on slide change, but it's possible in the pro version thanks to **onSlideChange** event. It takes as param FsLightbox instance. Unfortunately there is no previous slide number passed so you need to iterate through all sources:
```js
onSlideChange(fsLightbox) {
    const sources = fsLightbox.elements.sources;

    for (let i = 0; i < sources.length; i++) {
        const source = sources[i].current;
        if (source && source.tagName === 'VIDEO' && !source.paused) {
            source.pause();
        }
    }
}
```
