### ISSUE TITLE
Add null checks for localStorage

### ISSUE THREAD

**Issue by dmtrjs** [banthagroup/fslightbox-react#159]
There seems to be an error coming from this package:
```TypeError: null is not an object (evaluating 'localStorage.getItem')```.

 I suppose a null check is missing here. Disabling `localStorage` doesn't seem to help, as it is still being used in some places. 

Device: `iPhone`
Browser: `Mobile Safari 12.1.2`

**Comment by piotrzdziarski** [comment]
Since the version 1.6.1 you can disable all local storage operations by setting **disableLocalStorage** to **true**. This will fix this issue.
