### ISSUE TITLE
Don't remember "invalid" type in localStorage

### ISSUE THREAD

**Issue by Hypnosphi** [banthagroup/fslightbox-react#161]
Sometimes the type check fails because of network issues, but later it can pass. So it probably makes sense not to store "invalid" result forever.

Just to be clear: I know that I can avoid those checks at all by passing explicit media types or disable local storage with `disableLocalStorage`, but I think that it still makes sense to keep retrying after errors in "detect" mode

**Comment by piotrzdziarski** [comment]
Fixed in 1.6.0
