### ISSUE TITLE
Incorrect image loads after navigating through lightbox view

### ISSUE THREAD

**Issue by JeffMusgrave** [banthagroup/fslightbox-react#166]
This is specific to the react version and occurs on the demo on the fslightbox website as well. 

To reproduce:
- click on the first thumbnail to open the lightbox.
- click next image button one or more times.
- close the lightbox.
- click on the first thumbnail again.

The image that loads this time will be the last image displayed in the lightbox. So, if you closed the lightbox on image 5, when clicking thumbnail 1, it will open the lightbox and show image 5 instead of image 1. 

You can effectively reset this behaviour by clicking on another thumbnail at any point, then clicking the first thumbnail, which will result in the correct image being displayed in the lightbox.

**Comment by piotrzdziarski** [comment]
Workaround: reset slide state in **onClose** event listener, for example set it to null.

**Comment by piotrzdziarski** [comment]
Fixed in 1.6.1
